version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
      docker: 18
  pre_build:
    commands:
      - mvn test
  build:
    commands:
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 830802944459.dkr.ecr.eu-central-1.amazonaws.com
      - docker build -t incident_dashboard .
      - docker tag incident_dashboard:latest 830802944459.dkr.ecr.eu-central-1.amazonaws.com/incident_dashboard:latest
      - docker push 830802944459.dkr.ecr.eu-central-1.amazonaws.com/incident_dashboard:latest
#  post_build:
#    commands:
#      - echo Build completed on `date`
#      - mvn package
#      - mv target/bike-service-0.0.1-SNAPSHOT.war bike-service-0.0.1-SNAPSHOT.war
#artifacts:
#  files:
#    - bike-service-0.0.1-SNAPSHOT.war
#    - .ebextensions/**/*
#