version: '2'
services:
  incident-dashboard:
    container_name: incident-dashboard
    build:
      context: ./
      dockerfile: Dockerfile
    image: incident-dashboard:latest
    ports:
      - 18080:8080
    networks:
      - spring-cloud-network
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: incident-dashboard-mysql-compose
    image: mysql/mysql-server
    ports:
      - 33069:3306
    env_file:
      - ./src/main/resources/application.env
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge
